### ISSUE TITLE
Please add support for Statamic 5 and Laravel 11

### ISSUE THREAD

**Issue by Kaishiyoku** [daun/statamic-placeholders#1]
I'm upgrading a project at the moment and wanted to ask you if you could add support for Statamic 5 and Laravel 11 :)

**Comment by daun** [comment]
Hi! I'm not yet running any projects on the new Statamic version, but I'll look into it once I upgrade a project and get a chance of properly testing it. If you need this urgently, I'll happily accept a pull request with updated tests :)

**Comment by Kaishiyoku** [comment]
It's not urgent :)

**Comment by daun** [comment]
@Kaishiyoku I've released 2.1.0 with support for Statamic 5 and Laravel 11. I haven't yet installed it in an actual project, but tests are passing and there's no major breaking changes in the new Statamic version. Let me know if you run into any issues!

**Comment by Kaishiyoku** [comment]
Thank you :) I will try it out as soon as possible.

**Comment by Kaishiyoku** [comment]
It's working like a charm, thank you :)
