### ISSUE TITLE
Error encoding thumbhash: Unable to init from given binary data.

### ISSUE THREAD

**Issue by davidatkinswwt** [daun/statamic-placeholders#5]
I keep receiving this error. 

> Error encoding thumbhash: Unable to init from given binary data.

In my placeholders.php file I have:
'default_provider' => 'thumbhash',
'uri_format' => 'webp',

In the past I have had no issues with this, my assets are stored on a Digital Ocean Space. All my placeholders are able to be generated via the CLI. Additionally I cannot access the CP as this exception keeps popping up. 

Thanks

**Comment by daun** [comment]
Hi. Sounds like an empty image might be the problem here. When you say "in the past I had no issues with it" — did you upgrade to a newer version? Did you switch from local filesystem to DO?

**Comment by davidatkinswwt** [comment]
Hmm..ok that would make sense. 

In the past meaning I upgraded to Statamic 5.41 from 5.30. Downgrading yielded the same result. 

I've always used DO, since Statamic 3?

**Comment by daun** [comment]
There's probably two things I can do here:

1. check if we're ignoring empty images currently
2. not throw an exception when not inside an upload ajax request to avoid locking up the control panel

**Comment by davidatkinswwt** [comment]
I would appreciate that. I am at a total loss as to what is happening. I've looked for recent images I've uploaded that may be caused this error with no luck. 

I've regenerated all the placeholder images too.

**Comment by davidatkinswwt** [comment]
Just wanted to let you know I reverted back to a previous version of my site and everything is back to normal. 

I'll explore this more at a later date.

**Comment by daun** [comment]
Okay, good to know. Started looking into this a bit, this might be related to how the Laravel storage adapter reads binary files. Just for later reference if it comes up again — [Laravel Intervention - Unable to init from given binary data](https://stackoverflow.com/questions/72514083/laravel-intervention-unable-to-init-from-given-binary-data)
